CREATE DATABASE mydb;

ALTER SESSION SET CONTAINER = mydb;

CREATE USER dbuser IDENTIFIED BY dbpassword;

GRANT CONNECT, RESOURCE, DBA TO dbuser;

CREATE TABLE dbuser.users (
    id VARCHAR2(255) PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    address VARCHAR2(255) NOT NULL
);